### PR TITLE
Support Elm 0.17 module statement

### PR DESCRIPTION
**Pull request by shamansir**

### CODE REVIEW

**Comment by shamansir** [comment]
Lacks support of optional `port` at start of the module statement, will be in next PR.

But I think it's ok to publish as it is now.

**Comment by shamansir** [comment]
Now, also supports `port module <name> exposing <exports>` statements

**Comment by Bogdanp** [comment]
Thanks! I'll merge this and cut a release tomorrow morning.

**Comment by Bogdanp** [comment]
Published at http://package.elm-lang.org/packages/Bogdanp/elm-ast/latest .

**Pull request merged**
